### ISSUE TITLE
Rearrange widgets (feature request)

### ISSUE THREAD

**Issue by harryhaaren** [nicklan/drmr#2]
Feature request to rearrange the mapping of pads 1 - 16, to align them with hardware
such as drum machines and MIDI pads:
http://twinvulcan.com/wp-content/uploads/2011/10/akai2-pads.jpg

**Comment by nicklan** [comment]
Latest git can do this.  There is a combo box to select sample zero location.  Currently your choice won't be remembered across sessions, but you can set the default when you build DrMr by setting the SAMP_ZERO_POS cmake variable.  For the layout you want, set it to 1.

When I finally get the state extension stuff I'm working on merged in then your choice will be remembered for each session.

Thanks for the suggestion!

**Comment by harryhaaren** [comment]
Hmmm I must be doing something wrong...

cmake -DSAMP_ZERO_POS=1 . 
make

And zynjacku -> rescan -> load UI
shows the same UI as before... also don't see the mentioned combobox.

Hacked on the code in ui.c, line 450:
#ifdef DRMR_UI_ZERO_SAMP
  ui->startSamp = DRMR_UI_ZERO_SAMP;
#else
  ui->startSamp = 0;
#endif

nuked that to     ui->startSamp = 1;     still no avail...?

**Comment by nicklan** [comment]
Hrmm, that's very odd.  It sounds like you have the right code since you have the ifdefs in there.  silly question, but are you sure you installed after the re-compile (make install)? the fact that you're not seeing the combo box indicates to me that somehow the new lib isn't the one being loaded.

If you want to be totally sure, try putting:

printf("start samp: %i\n",ui->startSamp);

on line 85 of drmr_ui.c, and see if it prints that out and what the value is.

**Comment by harryhaaren** [comment]
On Sun, Mar 18, 2012 at 3:02 PM, Nick Lanham wrote:

>  but are you sure you installed after the re-compile (make install)?

Haha, and I concider myself a dev :D
Yeah that was it. Problems using tools I'm not normally using I spose.

Nice one thanks! -Harry
