### ISSUE TITLE
Sample preview button

### ISSUE THREAD

**Issue by naught101** [nicklan/drmr#6]
Loving the awesome sampler. Just what Linux audio needs right now (or at least, the part that I'm interesting in :D).

It would be really useful to have a sample preview button in the sample pane in the mane window. One reason is that if you're not familiar with the kit, then you really want to be able to check what it sounds like quickly and easily. Another is to check the sample gain and panning. 

Just a small button near the sample title would be suitable - or you could even make the sample title a button.

**Comment by nicklan** [comment]
Glad you're enjoying DrMr, always nice to hear :)

I completely agree with you, so much that there already is a sample preview button :)  The problem is, in pre-1.0 lv2 there is no good way for the UI to send a message to the core to say, please trigger this sample, so the master branch of DrMr doesn't have the preview button.  The lv2unstable branch has the feature.  If you look at [this screenshot](https://raw.github.com/wiki/nicklan/drmr/ardour_new_ui.png) you'll see the little green notification LED, which you can also click to trigger the sample.  

Whether the lv2unstable branch will work for you depends on what host you are using.  Jalv and Ardour3 both work fine, but as far as I know, qtractor doesn't yet have support for the new lv2 features the branch uses (specifically atoms).

But you can rest assured that, now that the lv2 spec has stabilized, most hosts should start supporting it soon.  I think once Ardour3 is out and QTractor supports lv2 1.0 I''ll make my lv2unstable branch master and you'll get all the nice new features in that branch.

**Comment by naught101** [comment]
Ah, awesome. Thanks for all the work!
