### ISSUE TITLE
LV2 interfaces see kit option as an index instead of a name

### ISSUE THREAD

**Issue by naught101** [nicklan/drmr#7]
When you load DrMr as an LV2 plugin within Qtractor, if you edit the plugin using Qtractors' interface, you can only see the drum kit index (integer), and not the drum kit title. This makes it pretty difficult to select which kit you want to use.

I don't know if it's possible to change this from DrMr - it might be a Qtractor problem. If it is, I'll submit a bug there.

**Comment by nicklan** [comment]
This is because the port is an integer port because string ports are not well supported in most hosts.  There's nothing I can do about it, and I don't think filing a bug against qtractor makes sense either.  It's basically just a weakness in the old lv2 spec.  The lv2unstable branch does indeed use a string (via an atom port) and so, when QTractor supports lv2 1.0, you will see a string instead of an integer.

This is all fixed in lv2 1.0.  As I noted in my reply to your other report, once qtractor and ardour3 support lv2 1.0 I'll release my lv2unstable branch as the main release.

**Comment by naught101** [comment]
Again, awesome. I will try out the unstable branch before posting new bugs :)
